name: Assignment Workflow

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
    
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/1075075215017/locations/global/workloadIdentityPools/github/providers/my-repo'

      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'public'
          destination: ''
          parent: false
